#!/usr/bin/env python3
"""llmcouncil adapter generator: canonical agents/ -> adapters/<runtime>/.

agents/ is the semantic source of truth (runtime-neutral seat definitions);
adapters/ is a mechanical projection of that source for each supported
runtime. Generated files are fully self-contained and committed so the skill
installs with a plain `cp`, without requiring Python at install time.

Sources:
  agents/_protocol.md   shared member contract with {{name}}, {{title}},
                        {{stance}} placeholders
  agents/<seat>.md      frontmatter (name, title, role, description, tools)
                        + stance body (role: member) or full body
                        (role: chairman)

Targets (one file per seat, plus a hand-written install.md that this script
never touches):
  adapters/claude/<name>.md      Claude Code   (YAML frontmatter markdown)
  adapters/opencode/<name>.md    OpenCode      (YAML frontmatter markdown)
  adapters/codex/<name>.toml     Codex CLI     (TOML)
  adapters/kimi/<name>.md        Kimi Code     (YAML frontmatter markdown)

Prerequisites: Python 3.8+, stdlib only.

Usage:
  generate_adapters.py            regenerate adapters/ (writes files, removes
                                  stale generated files, reports changes)
  generate_adapters.py --check    verify adapters/ match the canonical source
                                  without writing (for CI / invariants)
  generate_adapters.py --help

Exit codes:
  0  in sync (--check) / regeneration completed
  1  --check found drift, missing, or stale files
  2  usage error or invalid canonical source
"""

import argparse
import os
import re
import sys

SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENTS_DIR = os.path.join(SKILL_DIR, "agents")
ADAPTERS_DIR = os.path.join(SKILL_DIR, "adapters")
RUNTIMES = ("claude", "opencode", "codex", "kimi")

GENERATED_MD = ("<!-- GENERATED by scripts/generate_adapters.py from agents/ "
                "— do not edit; edit agents/ and regenerate. -->")
GENERATED_TOML = ("# GENERATED by scripts/generate_adapters.py from agents/ "
                  "— do not edit; edit agents/ and regenerate.")
KIMI_WHEN_TO_USE = ("Only when the llmcouncil skill's Clerk dispatches a "
                    "council request envelope; not for standalone use.")

REQUIRED_META = ("name", "title", "role", "description", "tools")
NAME_RE = re.compile(r"^council-[a-z][a-z-]*$")


def die(message):
    print("generate_adapters.py: %s" % message, file=sys.stderr)
    sys.exit(2)


def strip_leading_comment(text):
    """Drop one leading <!-- ... --> block (source-only guidance)."""
    text = text.lstrip("\n")
    if text.startswith("<!--"):
        end = text.find("-->")
        if end == -1:
            die("unterminated HTML comment in canonical source")
        text = text[end + 3:]
    return text.strip("\n")


def parse_canonical(path):
    with open(path, "r", encoding="utf-8") as fh:
        raw = fh.read()
    if not raw.startswith("---\n"):
        die("%s: missing frontmatter" % path)
    try:
        head, body = raw[4:].split("\n---\n", 1)
    except ValueError:
        die("%s: unterminated frontmatter" % path)
    meta = {}
    for line in head.splitlines():
        if not line.strip():
            continue
        if ":" not in line:
            die("%s: bad frontmatter line %r" % (path, line))
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip()
    for key in REQUIRED_META:
        if not meta.get(key):
            die("%s: missing frontmatter key %r" % (path, key))
    if not NAME_RE.match(meta["name"]):
        die("%s: name %r must match ^council-[a-z][a-z-]*$" % (path, meta["name"]))
    if meta["role"] not in ("member", "chairman"):
        die("%s: role must be 'member' or 'chairman'" % path)
    return meta, strip_leading_comment(body)


def load_seats():
    protocol_path = os.path.join(AGENTS_DIR, "_protocol.md")
    if not os.path.exists(protocol_path):
        die("missing %s" % protocol_path)
    with open(protocol_path, "r", encoding="utf-8") as fh:
        protocol = strip_leading_comment(fh.read())

    seats = []
    for entry in sorted(os.listdir(AGENTS_DIR)):
        if not entry.endswith(".md") or entry == "_protocol.md":
            continue
        meta, body = parse_canonical(os.path.join(AGENTS_DIR, entry))
        if meta["role"] == "member":
            full = (protocol
                    .replace("{{title}}", meta["title"])
                    .replace("{{name}}", meta["name"])
                    .replace("{{stance}}", body))
        else:
            full = body
        if "{{" in full:
            die("%s: unsubstituted placeholder in generated body" % entry)
        seats.append({"meta": meta, "body": full})

    names = [s["meta"]["name"] for s in seats]
    if len(seats) < 2 or len(set(names)) != len(names):
        die("need 2+ canonical seats with unique names, got %s" % names)
    if sum(1 for s in seats if s["meta"]["role"] == "chairman") != 1:
        die("exactly one canonical seat must have role: chairman")
    return seats


def render_claude(seat):
    m = seat["meta"]
    return (
        "---\n"
        "name: %s\n"
        "description: %s\n"
        "tools: %s\n"
        "model: inherit\n"
        "---\n"
        "%s\n\n"
        "%s\n" % (m["name"], m["description"], m["tools"], GENERATED_MD, seat["body"])
    )


def render_opencode(seat):
    m = seat["meta"]
    return (
        "---\n"
        "description: %s\n"
        "mode: subagent\n"
        "permission:\n"
        "  edit: deny\n"
        "  bash: deny\n"
        "---\n"
        "%s\n\n"
        "%s\n" % (m["description"], GENERATED_MD, seat["body"])
    )


def render_codex(seat):
    m = seat["meta"]
    if "'''" in seat["body"] or '"' in m["description"]:
        die("%s: body/description not representable in TOML literal strings"
            % m["name"])
    return (
        "%s\n"
        'name = "%s"\n'
        'description = "%s"\n'
        'sandbox_mode = "read-only"\n'
        "\n"
        "developer_instructions = '''\n"
        "%s\n"
        "'''\n" % (GENERATED_TOML, m["name"], m["description"], seat["body"])
    )


def render_kimi(seat):
    m = seat["meta"]
    return (
        "---\n"
        "name: %s\n"
        "description: %s\n"
        "whenToUse: %s\n"
        "tools: %s\n"
        "---\n"
        "%s\n\n"
        "%s\n" % (m["name"], m["description"], KIMI_WHEN_TO_USE, m["tools"],
                  GENERATED_MD, seat["body"])
    )


RENDERERS = {
    "claude": (render_claude, ".md"),
    "opencode": (render_opencode, ".md"),
    "codex": (render_codex, ".toml"),
    "kimi": (render_kimi, ".md"),
}


def expected_files(seats):
    out = {}
    for runtime in RUNTIMES:
        renderer, ext = RENDERERS[runtime]
        for seat in seats:
            rel = os.path.join(runtime, seat["meta"]["name"] + ext)
            out[rel] = renderer(seat)
    return out


def stale_files(expected):
    stale = []
    for runtime in RUNTIMES:
        directory = os.path.join(ADAPTERS_DIR, runtime)
        if not os.path.isdir(directory):
            continue
        for entry in sorted(os.listdir(directory)):
            rel = os.path.join(runtime, entry)
            if entry == "install.md" or rel in expected:
                continue
            if re.match(r"^council-[a-z][a-z-]*\.(md|toml)$", entry):
                stale.append(rel)
    return stale


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="generate_adapters.py",
        description="Regenerate adapters/<runtime>/ from canonical agents/ "
                    "(or verify they are in sync with --check).",
    )
    parser.add_argument("--check", action="store_true",
                        help="verify without writing; exit 1 on any drift")
    args = parser.parse_args(argv)

    expected = expected_files(load_seats())
    stale = stale_files(expected)
    drift, missing = [], []
    for rel, content in expected.items():
        path = os.path.join(ADAPTERS_DIR, rel)
        if not os.path.exists(path):
            missing.append(rel)
        else:
            with open(path, "r", encoding="utf-8") as fh:
                if fh.read() != content:
                    drift.append(rel)

    if args.check:
        for rel in missing:
            print("MISSING %s" % rel)
        for rel in drift:
            print("DRIFT   %s (differs from canonical source)" % rel)
        for rel in stale:
            print("STALE   %s (no canonical seat produces it)" % rel)
        if missing or drift or stale:
            print("RESULT: OUT OF SYNC (%d missing, %d drifted, %d stale) — "
                  "run generate_adapters.py to fix"
                  % (len(missing), len(drift), len(stale)))
            return 1
        print("RESULT: IN SYNC (%d files across %d runtimes)"
              % (len(expected), len(RUNTIMES)))
        return 0

    for rel in missing + drift:
        path = os.path.join(ADAPTERS_DIR, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(expected[rel])
        print("WROTE   %s" % rel)
    for rel in stale:
        os.remove(os.path.join(ADAPTERS_DIR, rel))
        print("REMOVED %s" % rel)
    unchanged = len(expected) - len(missing) - len(drift)
    print("RESULT: %d written, %d removed, %d unchanged"
          % (len(missing) + len(drift), len(stale), unchanged))
    return 0


if __name__ == "__main__":
    sys.exit(main())
